To install the NRPE (Nagios Remote Plugin Executor) agent on a remote server using Ansible, you can create an Ansible playbook. Here's a step-by-step guide:

**Step 1: Create an Ansible Playbook**

Create a YAML playbook, for example, `install_nrpe.yml`, and define the tasks for installing the NRPE agent.

```yaml
---
- name: Install NRPE Agent
  hosts: your_remote_server  # Replace with the target server's hostname or IP
  become: yes  # To run tasks with sudo privileges

  tasks:
    - name: Install NRPE Package
      package:
        name: nrpe
        state: present

    - name: Install Nagios Plugins
      package:
        name: nagios-plugins
        state: present

    - name: Start and Enable NRPE Service
      service:
        name: nrpe
        state: started
        enabled: yes
```

In this playbook:
- Replace `your_remote_server` with the actual hostname or IP address of the server where you want to install the NRPE agent.
- The `package` module is used to install the `nrpe` package, which contains the NRPE agent, and the `nagios-plugins` package, which contains a collection of plugins for monitoring.
- The `service` module is used to start and enable the NRPE service.

**Step 2: Execute the Ansible Playbook**

Run the playbook using the `ansible-playbook` command:

```bash
ansible-playbook install_nrpe.yml
```

Ansible will execute the tasks on the specified remote server, installing the NRPE agent and Nagios plugins. After the playbook execution is complete, the NRPE agent should be installed and running on the target server.

Make sure you have SSH access to the remote server and have Ansible properly configured to connect to it. Additionally, customize the playbook according to your specific requirements and environment.